using System;
using System.Collections.Generic;
using System.Text;

namespace BluetoothLE.Net.Parsers {

    /// <summary>
    /// This enum is nice for finding a string representation of a BT SIG assigned value for Characteristic UUIDs
    /// Reference: https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicsHome.aspx
    /// </summary>
    public enum GattNativeCharacteristicUuid : ushort {
        None = 0,

        DeviceName = 0x2A00,
        Appearance = 0x2A01,
        PeripheralPrivacyFlag = 0x2A02,
        ReconnectionAddress = 0x2A03,
        PeripheralPreferredConnectionParameters = 0x2A04,
        ServiceChanged = 0x2A05,
        AlertLevel = 0x2A06,
        TxPowerLevel = 0x2A07,
        DateTime = 0x2A08,
        DayofWeek = 0x2A09,
        DayDateTime = 0x2A0A,
        //ExactTime100 = 0x2A0B, //*
        ExactTime256 = 0x2A0C,
        DSTOffset = 0x2A0D,
        TimeZone = 0x2A0E,
        LocalTimeInformation = 0x2A0F,
        //SecondaryTimeZone = 0x2A10,//*
        TimewithDST = 0x2A11,
        TimeAccuracy = 0x2A12,
        TimeSource = 0x2A13,
        ReferenceTimeInformation = 0x2A14,
        //TimeBroadcast = 0x2A15,//*
        TimeUpdateControlPoint = 0x2A16,
        TimeUpdateState = 0x2A17,
        GlucoseMeasurement = 0x2A18,
        BatteryLevel = 0x2A19,
        //BatteryPowerState = 0x2A1A,
        //BatteryLevelState = 0x2A1B,
        TemperatureMeasurement = 0x2A1C,
        TemperatureType = 0x2A1D,
        IntermediateTemperature = 0x2A1E,
        //TemperatureinCelsius = 0x2A1F,  // apparently this one no longer exists ********
        //TemperatureinFahrenheit = 0x2A20,
        MeasurementInterval = 0x2A21,
        BootKeyboardInputReport = 0x2A22,
        SystemID = 0x2A23,
        ModelNumberString = 0x2A24,
        SerialNumberString = 0x2A25,
        FirmwareRevisionString = 0x2A26,
        HardwareRevisionString = 0x2A27,
        SoftwareRevisionString = 0x2A28,
        ManufacturerNameString = 0x2A29,
        IEEE11073_20601RegulatoryCertificationDataList = 0x2A2A,
        CurrentTime = 0x2A2B,
        ScanRefresh = 0x2A31,
        BootKeyboardOutputReport = 0x2A32,
        BootMouseInputReport = 0x2A33,
        GlucoseMeasurementContext = 0x2A34,
        BloodPressureMeasurement = 0x2A35,
        IntermediateCuffPressure = 0x2A36,
        HeartRateMeasurement = 0x2A37,
        BodySensorLocation = 0x2A38,
        HeartRateControlPoint = 0x2A39,
        //ScientificTemperatureinCelsius = 0x2A3C,
        //String = 0x2A3D,
        //NetworkAvailability = 0x2A3E,
        AlertStatus = 0x2A3F,
        RingerControlPoint = 0x2A40,
        RingerSetting = 0x2A41,
        AlertCategoryIDBitMask = 0x2A42,
        AlertCategoryID = 0x2A43,
        AlertNotificationControlPoint = 0x2A44,
        UnreadAlertStatus = 0x2A45,
        NewAlert = 0x2A46,
        SupportedNewAlertCategory = 0x2A47,
        SupportedUnreadAlertCategory = 0x2A48,
        BloodPressureFeature = 0x2A49,
        HIDInformation = 0x2A4A,
        ReportMap = 0x2A4B,
        HIDControlPoint = 0x2A4C,
        Report = 0x2A4D,
        ProtocolMode = 0x2A4E,
        ScanIntervalWindow = 0x2A4F,
        PnPID = 0x2A50,
        GlucoseFeature = 0x2A51,
        RecordAccessControlPoint = 0x2A52,
        RSCMeasurement = 0x2A53,
        RSCFeature = 0x2A54,
        SCControlPoint = 0x2A55,
        //DigitalInput = 0x2A56,
        //DigitalOutput = 0x2A57,
        //AnalogInput = 0x2A58,
        //AnalogOutput = 0x2A59,
        AggregateInput = 0x2A5A,
        CSCMeasurement = 0x2A5B,
        CSCFeature = 0x2A5C,
        SensorLocation = 0x2A5D,
        PulseOximetrySpotCheckMeasurement = 0x2A5E,
        PulseOximetryContinuousMeasurement = 0x2A5F,

        PulseOximetryFeatures = 0x2A60,
        //PulseOximetryPulsatileEvent = 0x2A60,
        //PulseOximetryControlPoint = 0x2A62,
        CyclingPowerMeasurement = 0x2A63,
        CyclingPowerVector = 0x2A64,
        CyclingPowerFeature = 0x2A65,
        CyclingPowerControlPoint = 0x2A66,
        LocationandSpeed = 0x2A67,
        Navigation = 0x2A68,
        PositionQuality = 0x2A69,
        LNFeature = 0x2A6A,
        LNControlPoint = 0x2A6B,
        Elevation = 0x2A6C, // Add to factory
        Pressure = 0x2A6D,
        Temperature = 0x2A6E,
        Humidity = 0x2A6F,

        // ---------------------------------
        // TODO Add all following to factory
        // ---------------------------------
        TrueWindSpeed = 0x2A70,
        TrueWindDirection = 0x2A71,
        ApparentWindSpeed = 0x2A72,
        ApparentWindDirection = 0x2A73,
        GustFactor = 0x2A74,
        PollenConcentration = 0x2A75,
        UVIndex =  0x2A76 ,
        Irradiance =  0x2A77, 
        Rainfall =  0x2A78 ,
        WindChill =  0x2A79, 
        HeatIndex =  0x2A7A ,
        DewPoint =  0x2A7B ,
        DescriptorValueChanged =  0x2A7D ,
        AerobicHeartRateLowerLimit =  0x2A7E ,
        AerobicThreshold =  0x2A7F ,
        Age =  0x2A80 ,
        AnaerobicHeartRateLowerLimit =  0x2A81 ,
        AnaerobicHeartRateUpperLimit =  0x2A82 ,
        AnaerobicThreshold =  0x2A83 ,
        AerobicHeartRateUpperLimit =  0x2A84 ,
        DateOfBirth =  0x2A85 ,
        DateOfThresholdAssessment =  0x2A86 ,
        EmailAddress =  0x2A87 ,
        FatBurnHeartRateLowerLimit =  0x2A88 ,
        FatBurnHeartRateUpperLimit =  0x2A89 ,
        FirstName =  0x2A8A ,
        FiveZoneHeartRateLimits =  0x2A8B ,
        Gender =  0x2A8C,
        /*


        Heart Rate Max =  0x2A8D ,
        Height =  0x2A8E ,
        Hip Circumference =  0x2A8F ,
        Last Name =  0x2A90 ,
        Maximum Recommended Heart Rate =  0x2A91 ,
        Resting Heart Rate =  0x2A92 ,
        Sport Type for Aerobic and Anaerobic Thresholds =  0x2A93,
        Three Zone Heart Rate Limits =  0x2A94 ,
        Two Zone Heart Rate Limits =  0x2A95 ,
        VO2 Max =  0x2A96 ,
        Waist Circumference =  0x2A97 ,
        Weight =  0x2A98 ,

        Database Change Increment =  0x2A99 
        User Index =  0x2A9A 
        Body Composition Feature =  0x2A9B 
        Body Composition Measurement =  0x2A9C 
        Weight Measurement =  0x2A9D 
        Weight Scale Feature =  0x2A9E 
        User Control Point =  0x2A9F 
        Magnetic Flux Density - 2D =  0x2AA0 
        Magnetic Flux Density - 3D =  0x2AA1 
        Language =  0x2AA2 
        Barometric Pressure Trend =  0x2AA3 
        Bond Management Control Point =  0x2AA4 
        Bond Management Feature =  0x2AA5 
        Central Address Resolution =  0x2AA6 
        CGM Measurement =  0x2AA7 
        CGM Feature =  0x2AA8 
        CGM Status =  0x2AA9 
        CGM Session Start Time =  0x2AAA 
        CGM Session Run Time =  0x2AAB 
        CGM Specific Ops Control Point =  0x2AAC 
        Indoor Positioning Configuration =  0x2AAD 
        Latitude =  0x2AAE 
        Longitude =  0x2AAF 
        Local North Coordinate =  0x2AB0 
        Local East Coordinate =  0x2AB1 
        Floor Number =  0x2AB2 
        Altitude =  0x2AB3 
        Uncertainty =  0x2AB4 
        Location Name =  0x2AB5 
        URI =  0x2AB6 
        HTTP Headers =  0x2AB7
        HTTP Status Code =  0x2AB8 
        HTTP Entity Body =  0x2AB9 
        HTTP Control Point =  0x2ABA 
        HTTPS Security =  0x2ABB 
        TDS Control Point =  0x2ABC 
        OTS Feature =  0x2ABD 
        object name =  0x2ABE 
        object type =  0x2ABF 
        object size =  0x2AC0 
        object first created =  0x2AC1 
        object last modified =  0x2AC2 
        object ID =  0x2AC3 
        object properties =  0x2AC4 
        object actioncontrol point =  0x2AC5 
        object list control point =  0x2AC6 
        object list filter =  0x2AC7 
        object changed =  0x2AC8 
        Resolvable Private Address Only =  0x2AC9 
        Unspecified =  0x2ACA 
        Directory Listing =  0x2ACB 
        Fitness Machine Feature =  0x2ACC 
        Treadmill Data =  0x2ACD 
        Cross Trainer Data =  0x2ACE 
        Step Climber Data =  0x2ACF 
        Stair Climber Data =  0x2AD0 
        Rower Data =  0x2AD1 
        Indoor Bike Data =  0x2AD2 
        Training Status =  0x2AD3 
        Supported Speed Range =  0x2AD4 
        Supported Inclination Range =  0x2AD5 
        Supported Resistance Level Range =  0x2AD6 
        Supported Heart Rate Range =  0x2AD7 
        Supported Power Range =  0x2AD8 
        Fitness Machine Control Point =  0x2AD9 
        Fitness Machine Status =  0x2ADA 
        Mesh Provisioning Data In =  0x2ADB 
        Mesh Provisioning Data Out =  0X2ADC 
        Mesh Proxy Data In =  0X2ADD
        Mesh Proxy Data Out =  0X2ADE 
        Average Current =  0X2AE0 
        Average Voltage =  0X2AE1 
        Boolean =  0X2AE2 
        Chromatic Distance From Planckian =  0X2AE3 
        Chromaticity Coordinates =  0X2AE4 
        Chromaticity in CCT And Duv Values =  0X2AE5 
        Chromaticity Tolerance =  0X2AE6 
        CIE 13.3-1995 Color Rendering Index =  0X2AE7 
        Coefficient =  0X2AE8 
        Correlated Color Temperature =  0X2AE9 
        Count 16 =  0X2AEA 
        Count 24 =  0X2AEB 
        Country Code =  0X2AEC 
        Date UTC =  0X2AED 
        Electric Current =  0X2AEE 
        Electric Current Range =  0X2AEF 
        Electric Current Specification =  0X2AF0 
        Electric Current Statistics =  0X2AF1 
        Energy =  0X2AF2 
        Energy In A Period Of Day =  0X2AF3 
        Event Statistics =  0X2AF4 
        Fixed String 16 =  0X2AF5 
        Fixed String 24 =  0X2AF6 
        Fixed String 36 =  0X2AF7 
        Fixed String 8 =  0X2AF8 
        Generic Level =  0X2AF9 
        Global Trade Item Number =  0X2AFA 
        Illuminance =  0X2AFB 
        Luminous Efficacy =  0X2AFC 
        Luminous Energy =  0X2AFD 
        Luminous Exposure =  0X2AFE 
        Luminous Flux =  0X2AFF 
        Luminous Flux Range =  0x2B00 
        Luminous Intensity =  0x2B01 
        Mass Flow =  0x2B02 
        Perceived Lightness =  0x2B03 
        Percentage 8 =  0x2B04 
        Power =  0x2B05 
        Power Specification =  0x2B06 
        Relative Runtime In A Current Range =  0x2B07 
        Relative Runtime In A Generic Level Range =  0x2B08 
        Relative Value In A Voltage Range =  0x2B09 
        Relative Value In An Illuminance Range =  0x2B0A 
        Relative Value In A Period Of Day =  0x2B0B 
        Relative Value In A Temperature Range =  0x2B0C 
        Temperature 8 =  0x2B0D 
        Temperature 8 In A Period Of Day =  0x2B0E 
        Temperature 8 Statistics =  0x2B0F 
        Temperature Range =  0x2B10 
        Temperature Statistics =  0x2B11 
        Time Decihour 8 =  0x2B12 
        Time Exponential 8 =  0x2B13 
        Time Hour 24 =  0x2B14 
        Time Millisecond 24 =  0x2B15 
        Time Second 16 =  0x2B16 
        Time Second 8 =  0x2B17 
        Voltage =  0x2B18 
        Voltage Specification =  0x2B19 
        Voltage Statistics =  0x2B1A 
        Volume Flow =  0x2B1B 
        Chromaticity Coordinate =  0x2B1C 
        RC Feature =  0x2B1D 
        RC Settings =  0x2B1E 
        Reconnection Configuration Control Point =  0x2B1F 
        IDD Status Changed =  0x2B20
        IDD Status =  0x2B21 
        IDD Annunciation Status =  0x2B22 
        IDD Features =  0x2B23 
        IDD Status Reader Control Point =  0x2B24 
        IDD Command Control Point =  0x2B25 
        IDD Command Data =  0x2B26 
        IDD Record Access Control Point =  0x2B27 
        IDD History Data =  0x2B28 
        Client Supported Features =  0x2B29 
        Database Hash =  0x2B2A 
        BSS Control Point =  0x2B2B 
        BSS Response =  0x2B2C 
        Emergency ID =  0x2B2D 
        Emergency Text =  0x2B2E 
        Enhanced Blood Pressure Measurement =  0x2B34 
        Enhanced Intermediate Cuff Pressure =  0x2B35 
        Blood Pressure Record =  0x2B36 
        BR-EDR Handover Data =  0x2B38 
        Bluetooth SIG Data =  0x2B39 
        Server Supported Features =  0x2B3A 
        Physical Activity Monitor Features =  0x2B3B 
        General Activity Instantaneous Data =  0x2B3C 
        General Activity Summary Data =  0x2B3D 
        CardioRespiratory Activity Instantaneous Data =  0x2B3E 
        CardioRespiratory Activity Summary Data =  0x2B3F 
        Step Counter Activity Summary Data =  0x2B40 
        Sleep Activity Instantaneous Data =  0x2B41 
        Sleep Activity Summary Data =  0x2B42 
        Physical Activity Monitor Control Point =  0x2B43 
        Current Session =  0x2B44 
        Session =  0x2B45 
        Preferred Units =  0x2B46 
        High Resolution Height =  0x2B47 
        Middle Name =  0x2B48 
        Stride Length =  0x2B49 
        Handedness =  0x2B4A
        Device Wearing Position =  0x2B4B 
        Four Zone Heart Rate Limits =  0x2B4C 
        High Intensity Exercise Threshold =  0x2B4D 
        Activity Goal =  0x2B4E 
        Sedentary Interval Notification =  0x2B4F 
        Caloric Intake =  0x2B50 
        Audio Input State =  0x2B77 
        Gain Settings Attribute =  0x2B78 
        Audio Input Type =  0x2B79 
        Audio Input Status =  0x2B7A 
        Audio Input Control Point =  0x2B7B 
        Audio Input Description =  0x2B7C 
        Volume State =  0x2B7D 
        Volume Control Point =  0x2B7E 
        Volume Flags =  0x2B7F 
        Offset State =  0x2B80 
        Audio Location =  0x2B81 
        Volume Offset Control Point =  0x2B82 
        Audio Output Description =  0x2B83 
        Device Time Feature =  0x2B8E 
        Device Time Parameters =  0x2B8F 
        Device Time =  0x2B90 
        Device Time Control Point =  0x2B91 
        Time Change Log Data =  0x2B92 
        Constant Tone Extension Enable =  0x2BAD 
        Advertising Constant Tone Extension Minimum Length =  0x2BAE 
        Advertising Constant Tone Extension Minimum Transmit Count =  0x2BAF 
        Advertising Constant Tone Extension Transmit Duration =  0x2BB0 
        Advertising Constant Tone Extension Interval =  0x2BB1 
        Advertising Constant Tone Extension PHY =  0x2BB2 
        */




        SimpleKeyState = 0xFFE1
    }
}
